#############################################################################
# Makefile for building: robot_control
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  robot_control.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile robot_control.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -O2 -std=c++11 -std=c++17 -isystem /usr/include/mit-krb5 -std=c++17 -pthread -std=c++17 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -std=c++11 -std=c++17 -isystem /usr/include/mit-krb5 -std=c++17 -pthread -std=c++17 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Cpp/lib/fuzzylite-6.0/fuzzylite -isystem /usr/include/gazebo-11 -isystem /usr/include/sdformat-9.3 -isystem /usr/include/ignition/fuel_tools4 -isystem /usr/include/x86_64-linux-gnu -isystem /usr/include/ignition/common3 -isystem /usr/include/ignition/transport8 -isystem /usr/include/pgm-5.2 -isystem /usr/include/uuid -isystem /usr/include/ignition/msgs5 -isystem /usr/include/ignition/math6 -isystem /usr/include/ignition/cmake2 -isystem /usr/include/opencv4/opencv -isystem /usr/include/opencv4 -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = robot_control1.0.0
DISTDIR = /home/th/Documents/RCA5-project/robot_control/.tmp/robot_control1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /home/th/Documents/Cpp/lib/fuzzylite-6.0/fuzzylite/release/bin/libfuzzylite-static.a /home/th/Documents/Cpp/lib/fuzzylite-6.0/fuzzylite/release/bin/libfuzzylite.so.6.0 /home/th/Documents/Cpp/lib/fuzzylite-6.0/fuzzylite/release/bin/libfuzzylite.so -L/usr/lib/x86_64-linux-gnu/gazebo-11/plugins -Wl,-rpath,/usr/lib/x86_64-linux-gnu/gazebo-11/plugins -lgazebo_transport -lgazebo_physics -lgazebo_sensors -lgazebo_rendering -lgazebo_gui -lgazebo_client -lgazebo_msgs -lgazebo_common -lgazebo -lboost_thread -lboost_system -lboost_filesystem -lboost_program_options -lboost_regex -lboost_iostreams -lboost_date_time -lsdformat9 -ltbb -latomic -lignition-fuel_tools4 -lignition-transport8 -luuid -lignition-msgs5 -lprotobuf -pthread -lignition-math6 -ltinyxml2 -lopencv_stitching -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn_objdetect -lopencv_dnn_superres -lopencv_dpm -lopencv_highgui -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_hfs -lopencv_img_hash -lopencv_line_descriptor -lopencv_quality -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_shape -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_superres -lopencv_optflow -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_dnn -lopencv_plot -lopencv_ml -lopencv_videostab -lopencv_videoio -lopencv_viz -lopencv_ximgproc -lopencv_video -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_imgcodecs -lopencv_features2d -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_imgproc -lopencv_core   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		../../../.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		robot_control.pro  main.cpp
QMAKE_TARGET  = robot_control
DESTDIR       = 
TARGET        = robot_control


first: all
####### Build rules

robot_control:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: robot_control.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		../../../.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		robot_control.pro
	$(QMAKE) -o Makefile robot_control.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
../../../.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
robot_control.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile robot_control.pro

qmake_all: FORCE


all: Makefile robot_control

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp ../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/Headers.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/fuzzylite.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/Benchmark.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/Complexity.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/imex/FldExporter.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/imex/Exporter.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/Console.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/Engine.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/Exception.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/activation/Activation.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/activation/First.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/activation/General.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/activation/Highest.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/activation/Last.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/activation/Lowest.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/activation/Proportional.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/activation/Threshold.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/defuzzifier/Bisector.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/defuzzifier/IntegralDefuzzifier.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/defuzzifier/Defuzzifier.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/defuzzifier/Centroid.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/defuzzifier/SmallestOfMaximum.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/defuzzifier/LargestOfMaximum.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/defuzzifier/MeanOfMaximum.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/defuzzifier/WeightedAverage.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/defuzzifier/WeightedDefuzzifier.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/defuzzifier/WeightedSum.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/factory/ActivationFactory.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/factory/ConstructionFactory.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/hedge/Hedge.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/SNorm.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/Norm.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/TNorm.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/Term.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/Operation.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/factory/CloningFactory.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/factory/FactoryManager.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/factory/TNormFactory.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/factory/SNormFactory.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/factory/DefuzzifierFactory.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/factory/TermFactory.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/factory/HedgeFactory.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/factory/FunctionFactory.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/Function.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/imex/CppExporter.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/imex/FclImporter.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/imex/Importer.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/imex/FclExporter.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/imex/FisImporter.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/imex/FisExporter.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/imex/FllImporter.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/imex/FllExporter.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/imex/JavaExporter.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/imex/RScriptExporter.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/hedge/Any.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/hedge/Extremely.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/hedge/HedgeFunction.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/hedge/Not.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/hedge/Seldom.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/hedge/Somewhat.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/hedge/Very.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/s/AlgebraicSum.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/s/BoundedSum.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/s/DrasticSum.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/s/EinsteinSum.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/s/HamacherSum.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/s/Maximum.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/s/NilpotentMaximum.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/s/NormalizedSum.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/s/SNormFunction.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/s/UnboundedSum.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/t/AlgebraicProduct.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/t/BoundedDifference.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/t/DrasticProduct.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/t/EinsteinProduct.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/t/HamacherProduct.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/t/Minimum.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/t/NilpotentMinimum.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/norm/t/TNormFunction.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/rule/Antecedent.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/rule/Consequent.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/rule/Rule.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/rule/RuleBlock.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/rule/Expression.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/Aggregated.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/Activated.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/Bell.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/Binary.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/Concave.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/Constant.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/Cosine.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/Discrete.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/Gaussian.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/GaussianProduct.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/Linear.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/PiShape.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/Ramp.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/Rectangle.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/SShape.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/Sigmoid.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/SigmoidDifference.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/SigmoidProduct.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/Spike.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/Trapezoid.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/Triangle.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/term/ZShape.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/variable/InputVariable.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/variable/Variable.h \
		../../Cpp/lib/fuzzylite-6.0/fuzzylite/fl/variable/OutputVariable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

